### PR TITLE
Add rxjs-primitives

### PR DESCRIPTION
**Pull request by tanepiper**
Adding my rxjs-primitives library - itself it's not one library, but a collection under one name - each library is listed with npm install and link to API documentation

### CODE REVIEW

**Comment by cartant** [comment]
Thanks.

> ... itself it's not one library, but a collection under one name ...

It would be best if you added an entry for each package, as the `title` in the frontmatter is used to build a link to the npm package. Have a look at the two entries that I created for Michael Hladky's `@rx-angular` packages. There are two, but both reside in the same mono repo - which seems to be the situation for your packages, too.

I'm not worried about having lots of packages listed on the sites home page. When I next deploy it, it'll have a full text search box at the top, so filtering the list will be easy.

**Comment by tanepiper** [comment]
@cartant No problem, I wasn't sure how you'd feel about me adding 5 libraries, but I can sort that out.

**Comment by cartant** [comment]
Thanks. I've updated the `CONTRIBUTING` doc to make it a little clearer that the `title` is the (potentially scoped) package name.

**Review by cartant — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
